"""Add pais_origen to Laboratorio

Revision ID: 42e3e64d9fc7
Revises: 2c99e3aaece6
Create Date: 2025-09-07 16:54:08.357393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42e3e64d9fc7'
down_revision: Union[str, Sequence[str], None] = '2c99e3aaece6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerta', sa.Column('prioridad', sa.String(length=20), nullable=True))
    op.add_column('alerta', sa.Column('id_seccion', sa.Integer(), nullable=True))
    op.add_column('alerta', sa.Column('dias_para_vencer', sa.Integer(), nullable=True))
    op.add_column('alerta', sa.Column('stock_actual', sa.Integer(), nullable=True))
    op.add_column('alerta', sa.Column('stock_minimo', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'alerta', 'seccion', ['id_seccion'], ['id_seccion'])
    op.add_column('laboratorio', sa.Column('pais_origen', sa.String(length=100), nullable=True))
    op.drop_column('producto', 'stock_maximo')
    op.drop_column('producto', 'fecha_vencimiento')
    op.drop_column('producto', 'precio_venta')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('precio_venta', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('producto', sa.Column('fecha_vencimiento', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('producto', sa.Column('stock_maximo', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('laboratorio', 'pais_origen')
    op.drop_constraint(None, 'alerta', type_='foreignkey')
    op.drop_column('alerta', 'stock_minimo')
    op.drop_column('alerta', 'stock_actual')
    op.drop_column('alerta', 'dias_para_vencer')
    op.drop_column('alerta', 'id_seccion')
    op.drop_column('alerta', 'prioridad')
    # ### end Alembic commands ###
