"""add_usuario_table

Revision ID: 12453312962c
Revises: 813e6b3d7b9a
Create Date: 2025-09-06 02:51:49.711715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12453312962c'
down_revision: Union[str, Sequence[str], None] = '813e6b3d7b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_alerta_id_alerta'), 'alerta', ['id_alerta'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerta_id_alerta'), table_name='alerta')
    # ### end Alembic commands ###
