"""restructure all models with relationships

Revision ID: 813e6b3d7b9a
Revises: 8b0b2b1251ba
Create Date: 2025-09-05 21:18:22.120366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '813e6b3d7b9a'
down_revision: Union[str, Sequence[str], None] = '8b0b2b1251ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerta', 'tipo_alerta',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('alerta', 'mensaje',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('alerta', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'Activo'::character varying"))
    # Actualiza los valores nulos a 'Desconocido' antes de aplicar NOT NULL
    op.execute("UPDATE cliente SET apellido_cliente = 'Desconocido' WHERE apellido_cliente IS NULL")
    op.alter_column('cliente', 'apellido_cliente',
                    existing_type=sa.VARCHAR(length=100),
                    nullable=False)
    # op.add_column('detalle_venta', sa.Column('id_detalle', sa.Integer(), nullable=False))
    # op.add_column('detalle_venta', sa.Column('id_detalle', sa.Integer(), nullable=False))
    op.alter_column('detalle_venta', 'precio_unitario',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('detalle_venta', 'subtotal',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_index(op.f('ix_detalle_venta_id_detalle'), 'detalle_venta', ['id_detalle'], unique=False)
    op.drop_column('detalle_venta', 'id_detalle_venta')
    # Agregar columna 'cantidad' sin restricción NOT NULL inicialmente
    op.add_column('entrada', sa.Column('cantidad', sa.Integer(), nullable=True))
    # Actualizar valores NULL a 0 (o el valor predeterminado que prefieras)
    op.execute("UPDATE entrada SET cantidad = 0 WHERE cantidad IS NULL")
    # Modificar la columna para establecer NOT NULL
    op.alter_column('entrada', 'cantidad', existing_type=sa.Integer(), nullable=False)
    op.alter_column('entrada', 'precio_compra_unitario',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('entrada', 'precio_compra_total',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_index(op.f('ix_entrada_id_entrada'), 'entrada', ['id_entrada'], unique=False)
    op.drop_column('entrada', 'estado')
    # Agregar columna 'cantidad_inicial' sin restricción NOT NULL inicialmente
    op.add_column('lote', sa.Column('cantidad_inicial', sa.Integer(), nullable=True))
    # Actualizar valores NULL a 0 (o el valor predeterminado que prefieras)
    op.execute("UPDATE lote SET cantidad_inicial = 0 WHERE cantidad_inicial IS NULL")
    # Modificar la columna para establecer NOT NULL
    op.alter_column('lote', 'cantidad_inicial', existing_type=sa.Integer(), nullable=False)
    op.add_column('lote', sa.Column('fecha_produccion', sa.DateTime(), nullable=True))
    op.alter_column('lote', 'numero_lote',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('lote', 'fecha_vencimiento',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
    op.alter_column('lote', 'precio_compra_lote',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('lote', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'Activo'::character varying"))
    op.create_index(op.f('ix_lote_id_lote'), 'lote', ['id_lote'], unique=False)
    op.drop_column('lote', 'fecha_entrada')
    op.add_column('producto', sa.Column('codigo_barras', sa.String(length=50), nullable=True))
    op.add_column('producto', sa.Column('requiere_receta', sa.Boolean(), nullable=True))
    op.alter_column('producto', 'precio_compra',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('producto', 'precio_venta')
    op.drop_column('producto', 'fecha_vencimiento')
    op.drop_column('producto', 'lote')
    op.drop_column('producto', 'stock_maximo')
    op.add_column('rol', sa.Column('permisos', sa.Text(), nullable=True))
    op.alter_column('rol', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.create_index(op.f('ix_rol_id_rol'), 'rol', ['id_rol'], unique=False)
    op.drop_column('rol', 'estado')
    # Agregar columna 'cantidad' sin restricción NOT NULL inicialmente
    op.add_column('salida', sa.Column('cantidad', sa.Integer(), nullable=True))
    # Actualizar valores NULL a 0 (o el valor predeterminado que prefieras)
    op.execute("UPDATE salida SET cantidad = 0 WHERE cantidad IS NULL")
    # Modificar la columna para establecer NOT NULL
    op.alter_column('salida', 'cantidad', existing_type=sa.Integer(), nullable=False)
    op.add_column('salida', sa.Column('tipo_salida', sa.String(length=50), nullable=True))
    op.alter_column('salida', 'motivo',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_index(op.f('ix_salida_id_salida'), 'salida', ['id_salida'], unique=False)
    op.drop_column('salida', 'cantidad_salida')
    op.drop_column('salida', 'estado')
    op.add_column('seccion', sa.Column('capacidad_maxima', sa.Integer(), nullable=True))
    op.add_column('seccion', sa.Column('temperatura_recomendada', sa.String(length=50), nullable=True))
    op.add_column('seccion', sa.Column('fecha_ultimo_mantenimiento', sa.DateTime(), nullable=True))
    op.alter_column('seccion', 'nombre_seccion',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_unique_constraint(None, 'seccion', ['nombre_seccion'])
    op.add_column('usuario', sa.Column('nombre_completo', sa.String(length=100), nullable=True))
    op.add_column('usuario', sa.Column('ultima_acceso', sa.DateTime(), nullable=True))
    op.alter_column('usuario', 'nombre_usuario',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('usuario', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('usuario', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('usuario', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('usuario', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'Activo'::character varying"))
    op.drop_constraint(op.f('usuario_email_key'), 'usuario', type_='unique')
    op.create_index(op.f('ix_usuario_id_usuario'), 'usuario', ['id_usuario'], unique=False)
    op.create_unique_constraint(None, 'usuario', ['nombre_usuario'])
    op.drop_column('usuario', 'ultimo_acceso')
    op.drop_column('usuario', 'cedula')
    op.add_column('venta', sa.Column('impuestos', sa.Float(), nullable=True))
    op.alter_column('venta', 'subtotal',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('venta', 'descuento',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('venta', 'total',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('venta', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'Completado'::character varying"))
    op.create_index(op.f('ix_venta_id_venta'), 'venta', ['id_venta'], unique=False)
    op.drop_column('venta', 'impuesto')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venta', sa.Column('impuesto', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_venta_id_venta'), table_name='venta')
    op.alter_column('venta', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'Completado'::character varying"))
    op.alter_column('venta', 'total',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('venta', 'descuento',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('venta', 'subtotal',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('venta', 'impuestos')
    op.add_column('usuario', sa.Column('cedula', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('usuario', sa.Column('ultimo_acceso', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'usuario', type_='unique')
    op.drop_index(op.f('ix_usuario_id_usuario'), table_name='usuario')
    op.create_unique_constraint(op.f('usuario_email_key'), 'usuario', ['email'])
    op.alter_column('usuario', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'Activo'::character varying"))
    op.alter_column('usuario', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('usuario', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('usuario', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('usuario', 'nombre_usuario',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('usuario', 'ultima_acceso')
    op.drop_column('usuario', 'nombre_completo')
    op.drop_constraint(None, 'seccion', type_='unique')
    op.alter_column('seccion', 'nombre_seccion',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('seccion', 'fecha_ultimo_mantenimiento')
    op.drop_column('seccion', 'temperatura_recomendada')
    op.drop_column('seccion', 'capacidad_maxima')
    op.add_column('salida', sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'Completado'::character varying"), autoincrement=False, nullable=False))
    op.add_column('salida', sa.Column('cantidad_salida', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_salida_id_salida'), table_name='salida')
    op.alter_column('salida', 'motivo',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('salida', 'cantidad')
    op.drop_column('salida', 'tipo_salida')
    op.add_column('rol', sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'Activo'::character varying"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_rol_id_rol'), table_name='rol')
    op.alter_column('rol', 'descripcion',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('rol', 'permisos')
    op.add_column('producto', sa.Column('stock_maximo', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('producto', sa.Column('lote', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('producto', sa.Column('fecha_vencimiento', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('producto', sa.Column('precio_venta', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.alter_column('producto', 'precio_compra',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('producto', 'requiere_receta')
    op.drop_column('producto', 'codigo_barras')
    op.add_column('lote', sa.Column('fecha_entrada', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_lote_id_lote'), table_name='lote')
    op.alter_column('lote', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'Activo'::character varying"))
    op.alter_column('lote', 'precio_compra_lote',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('lote', 'fecha_vencimiento',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
    op.alter_column('lote', 'numero_lote',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('lote', 'cantidad_inicial')
    op.drop_column('lote', 'fecha_produccion')
    op.add_column('entrada', sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'Completado'::character varying"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_entrada_id_entrada'), table_name='entrada')
    op.alter_column('entrada', 'precio_compra_total',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('entrada', 'precio_compra_unitario',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('entrada', 'cantidad')
    op.add_column('detalle_venta', sa.Column('id_detalle_venta', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_detalle_venta_id_detalle'), table_name='detalle_venta')
    op.alter_column('detalle_venta', 'subtotal',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('detalle_venta', 'precio_unitario',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('detalle_venta', 'id_detalle')
    op.alter_column('cliente', 'apellido_cliente',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_alerta_id_alerta'), table_name='alerta')
    op.alter_column('alerta', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'Activo'::character varying"))
    op.alter_column('alerta', 'mensaje',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('alerta', 'tipo_alerta',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venta', sa.Column('impuesto', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_venta_id_venta'), table_name='venta')
    op.alter_column('venta', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'Completado'::character varying"))
    op.alter_column('venta', 'total',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('venta', 'descuento',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('venta', 'subtotal',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('venta', 'impuestos')
    op.add_column('usuario', sa.Column('cedula', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('usuario', sa.Column('ultimo_acceso', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'usuario', type_='unique')
    op.drop_index(op.f('ix_usuario_id_usuario'), table_name='usuario')
    op.create_unique_constraint(op.f('usuario_email_key'), 'usuario', ['email'])
    op.alter_column('usuario', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'Activo'::character varying"))
    op.alter_column('usuario', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('usuario', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('usuario', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('usuario', 'nombre_usuario',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('usuario', 'ultima_acceso')
    op.drop_column('usuario', 'nombre_completo')
    op.drop_constraint(None, 'seccion', type_='unique')
    op.alter_column('seccion', 'nombre_seccion',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('seccion', 'fecha_ultimo_mantenimiento')
    op.drop_column('seccion', 'temperatura_recomendada')
    op.drop_column('seccion', 'capacidad_maxima')
    op.add_column('salida', sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'Completado'::character varying"), autoincrement=False, nullable=False))
    op.add_column('salida', sa.Column('cantidad_salida', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_salida_id_salida'), table_name='salida')
    op.alter_column('salida', 'motivo',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('salida', 'cantidad')
    op.drop_column('salida', 'tipo_salida')
    op.add_column('rol', sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'Activo'::character varying"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_rol_id_rol'), table_name='rol')
    op.alter_column('rol', 'descripcion',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('rol', 'permisos')
    op.add_column('producto', sa.Column('stock_maximo', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('producto', sa.Column('lote', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('producto', sa.Column('fecha_vencimiento', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('producto', sa.Column('precio_venta', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.alter_column('producto', 'precio_compra',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('producto', 'requiere_receta')
    op.drop_column('producto', 'codigo_barras')
    op.add_column('lote', sa.Column('fecha_entrada', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_lote_id_lote'), table_name='lote')
    op.alter_column('lote', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'Activo'::character varying"))
    op.alter_column('lote', 'precio_compra_lote',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('lote', 'fecha_vencimiento',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
    op.alter_column('lote', 'numero_lote',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('lote', 'cantidad_inicial')
    op.drop_column('lote', 'fecha_produccion')
    op.add_column('entrada', sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'Completado'::character varying"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_entrada_id_entrada'), table_name='entrada')
    op.alter_column('entrada', 'precio_compra_total',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('entrada', 'precio_compra_unitario',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('entrada', 'cantidad')
    op.add_column('detalle_venta', sa.Column('id_detalle_venta', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_detalle_venta_id_detalle'), table_name='detalle_venta')
    op.alter_column('detalle_venta', 'subtotal',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('detalle_venta', 'precio_unitario',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('detalle_venta', 'id_detalle')
    op.alter_column('cliente', 'apellido_cliente',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_alerta_id_alerta'), table_name='alerta')
    op.alter_column('alerta', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'Activo'::character varying"))
    op.alter_column('alerta', 'mensaje',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('alerta', 'tipo_alerta',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###