"""Creación de tablas inicial

Revision ID: 8b0b2b1251ba
Revises: 
Create Date: 2025-09-02 20:18:29.226550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b0b2b1251ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('lote')
    # op.drop_table('salida')
    # op.drop_table('rol')
    # op.drop_table('venta')
    # op.drop_table('detalle_venta')
    # op.drop_table('entrada')
    # op.drop_table('usuario')
    # op.drop_table('alerta')
    op.add_column('cliente', sa.Column('apellido_cliente', sa.String(), nullable=True))  # Cambiado a nullable=True
    op.alter_column('cliente', 'cedula',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('cliente', 'direccion',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('cliente', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'Activo'::character varying"))
    op.create_index(op.f('ix_cliente_id_cliente'), 'cliente', ['id_cliente'], unique=False)
    op.create_unique_constraint(None, 'cliente', ['cedula'])
    op.alter_column('laboratorio', 'direccion',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('laboratorio', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'Activo'::character varying"))
    op.create_index(op.f('ix_laboratorio_id_laboratorio'), 'laboratorio', ['id_laboratorio'], unique=False)
    op.alter_column('producto', 'precio_compra',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('producto', 'stock_actual',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('producto', 'stock_minimo',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('producto', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('producto', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'Activo'::character varying"))
    op.create_index(op.f('ix_producto_id_producto'), 'producto', ['id_producto'], unique=False)
    op.drop_column('producto', 'codigo_barras')
    op.drop_column('producto', 'requiere_receta')
    op.alter_column('seccion', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('seccion', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'Activo'::character varying"))
    op.create_index(op.f('ix_seccion_id_seccion'), 'seccion', ['id_seccion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seccion_id_seccion'), table_name='seccion')
    op.alter_column('seccion', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'Activo'::character varying"))
    op.alter_column('seccion', 'descripcion',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('producto', sa.Column('requiere_receta', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('producto', sa.Column('codigo_barras', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_producto_id_producto'), table_name='producto')
    op.alter_column('producto', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'Activo'::character varying"))
    op.alter_column('producto', 'descripcion',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('producto', 'stock_minimo',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('producto', 'stock_actual',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('producto', 'precio_compra',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.drop_index(op.f('ix_laboratorio_id_laboratorio'), table_name='laboratorio')
    op.alter_column('laboratorio', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'Activo'::character varying"))
    op.alter_column('laboratorio', 'direccion',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'cliente', type_='unique')
    op.drop_index(op.f('ix_cliente_id_cliente'), table_name='cliente')
    op.alter_column('cliente', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'Activo'::character varying"))
    op.alter_column('cliente', 'direccion',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('cliente', 'cedula',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('cliente', 'apellido_cliente')
    op.create_table('alerta',
    sa.Column('id_alerta', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipo_alerta', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('mensaje', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('fecha_resolucion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'Activo'::character varying"), autoincrement=False, nullable=False),
    sa.Column('id_producto', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id_producto'], name=op.f('alerta_id_producto_fkey')),
    sa.PrimaryKeyConstraint('id_alerta', name=op.f('alerta_pkey'))
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.INTEGER(), server_default=sa.text("nextval('usuario_id_usuario_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre_usuario', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('cedula', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('ultimo_acceso', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'Activo'::character varying"), autoincrement=False, nullable=False),
    sa.Column('id_rol', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id_rol'], name='usuario_id_rol_fkey'),
    sa.PrimaryKeyConstraint('id_usuario', name='usuario_pkey'),
    sa.UniqueConstraint('email', name='usuario_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('entrada',
    sa.Column('id_entrada', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha_entrada', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('precio_compra_unitario', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('precio_compra_total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('numero_factura_compra', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('proveedor', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('observaciones', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'Completado'::character varying"), autoincrement=False, nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_lote', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id_lote'], name=op.f('entrada_id_lote_fkey')),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], name=op.f('entrada_id_usuario_fkey')),
    sa.PrimaryKeyConstraint('id_entrada', name=op.f('entrada_pkey'))
    )
    op.create_table('detalle_venta',
    sa.Column('id_detalle_venta', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('precio_unitario', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('subtotal', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('id_venta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_lote', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id_lote'], name=op.f('detalle_venta_id_lote_fkey')),
    sa.ForeignKeyConstraint(['id_venta'], ['venta.id_venta'], name=op.f('detalle_venta_id_venta_fkey')),
    sa.PrimaryKeyConstraint('id_detalle_venta', name=op.f('detalle_venta_pkey'))
    )
    op.create_table('venta',
    sa.Column('id_venta', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha_venta', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('subtotal', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('descuento', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.Column('impuesto', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('metodo_pago', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'Completado'::character varying"), autoincrement=False, nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_cliente', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], name=op.f('venta_id_cliente_fkey')),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], name=op.f('venta_id_usuario_fkey')),
    sa.PrimaryKeyConstraint('id_venta', name=op.f('venta_pkey'))
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.INTEGER(), server_default=sa.text("nextval('rol_id_rol_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre_rol', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'Activo'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_rol', name='rol_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('salida',
    sa.Column('id_salida', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha_salida', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('cantidad_salida', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('motivo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('observaciones', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'Completado'::character varying"), autoincrement=False, nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_lote', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id_lote'], name=op.f('salida_id_lote_fkey')),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], name=op.f('salida_id_usuario_fkey')),
    sa.PrimaryKeyConstraint('id_salida', name=op.f('salida_pkey'))
    )
    op.create_table('lote',
    sa.Column('id_lote', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('numero_lote', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('fecha_vencimiento', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('fecha_entrada', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('cantidad_disponible', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('precio_compra_lote', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('temperatura_almacenamiento', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'Activo'::character varying"), autoincrement=False, nullable=False),
    sa.Column('id_producto', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id_producto'], name=op.f('lote_id_producto_fkey')),
    sa.PrimaryKeyConstraint('id_lote', name=op.f('lote_pkey'))
    )
    # ### end Alembic commands ###
