"""initial_complete_schema

Revision ID: e8ab0da0fd4b
Revises: 
Create Date: 2025-11-10 10:24:00.988590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8ab0da0fd4b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('nombre_cliente', sa.String(length=100), nullable=False),
    sa.Column('apellido_cliente', sa.String(length=100), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('cedula')
    )
    op.create_index(op.f('ix_cliente_id_cliente'), 'cliente', ['id_cliente'], unique=False)
    op.create_table('laboratorio',
    sa.Column('id_laboratorio', sa.Integer(), nullable=False),
    sa.Column('nombre_laboratorio', sa.String(length=100), nullable=False),
    sa.Column('pais_origen', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_laboratorio')
    )
    op.create_index(op.f('ix_laboratorio_id_laboratorio'), 'laboratorio', ['id_laboratorio'], unique=False)
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('permisos', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_index(op.f('ix_rol_id_rol'), 'rol', ['id_rol'], unique=False)
    op.create_table('seccion',
    sa.Column('id_seccion', sa.Integer(), nullable=False),
    sa.Column('nombre_seccion', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('ubicacion_fisica', sa.String(length=100), nullable=True),
    sa.Column('capacidad_maxima', sa.Integer(), nullable=True),
    sa.Column('temperatura_recomendada', sa.String(length=50), nullable=True),
    sa.Column('fecha_ultimo_mantenimiento', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_seccion'),
    sa.UniqueConstraint('nombre_seccion')
    )
    op.create_index(op.f('ix_seccion_id_seccion'), 'seccion', ['id_seccion'], unique=False)
    op.create_table('producto',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_seccion', sa.Integer(), nullable=False),
    sa.Column('id_laboratorio', sa.Integer(), nullable=False),
    sa.Column('nombre_producto', sa.String(length=100), nullable=False),
    sa.Column('principio_activo', sa.String(length=100), nullable=True),
    sa.Column('concentracion', sa.String(length=50), nullable=True),
    sa.Column('forma_farmaceutica', sa.String(length=50), nullable=True),
    sa.Column('codigo_barras', sa.String(length=50), nullable=True),
    sa.Column('requiere_receta', sa.Boolean(), nullable=True),
    sa.Column('precio_compra', sa.Float(), nullable=False),
    sa.Column('stock_actual', sa.Integer(), nullable=True),
    sa.Column('stock_minimo', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_laboratorio'], ['laboratorio.id_laboratorio'], ),
    sa.ForeignKeyConstraint(['id_seccion'], ['seccion.id_seccion'], ),
    sa.PrimaryKeyConstraint('id_producto'),
    sa.UniqueConstraint('codigo_barras')
    )
    op.create_index(op.f('ix_producto_estado'), 'producto', ['estado'], unique=False)
    op.create_index(op.f('ix_producto_id_producto'), 'producto', ['id_producto'], unique=False)
    op.create_index(op.f('ix_producto_nombre_producto'), 'producto', ['nombre_producto'], unique=False)
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=True),
    sa.Column('nombre_usuario', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('nombre_completo', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('ultima_acceso', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('codigo_recuperacion', sa.String(length=10), nullable=True),
    sa.Column('codigo_recuperacion_expiry', sa.DateTime(), nullable=True),
    sa.Column('reset_attempts', sa.Integer(), nullable=True),
    sa.Column('reset_locked_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('nombre_usuario')
    )
    op.create_index(op.f('ix_usuario_id_usuario'), 'usuario', ['id_usuario'], unique=False)
    op.create_table('alerta',
    sa.Column('id_alerta', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('tipo_alerta', sa.String(length=50), nullable=True),
    sa.Column('prioridad', sa.String(length=20), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_resolucion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('id_seccion', sa.Integer(), nullable=True),
    sa.Column('dias_para_vencer', sa.Integer(), nullable=True),
    sa.Column('stock_actual', sa.Integer(), nullable=True),
    sa.Column('stock_minimo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id_producto'], ),
    sa.ForeignKeyConstraint(['id_seccion'], ['seccion.id_seccion'], ),
    sa.PrimaryKeyConstraint('id_alerta')
    )
    op.create_index(op.f('ix_alerta_id_alerta'), 'alerta', ['id_alerta'], unique=False)
    op.create_table('gasto',
    sa.Column('id_gasto', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('fecha_gasto', sa.DateTime(), nullable=False),
    sa.Column('concepto', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('numero_factura', sa.String(length=50), nullable=True),
    sa.Column('proveedor', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_gasto')
    )
    op.create_index(op.f('ix_gasto_categoria'), 'gasto', ['categoria'], unique=False)
    op.create_index(op.f('ix_gasto_fecha_gasto'), 'gasto', ['fecha_gasto'], unique=False)
    op.create_index(op.f('ix_gasto_id_gasto'), 'gasto', ['id_gasto'], unique=False)
    op.create_table('lote',
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('numero_lote', sa.String(length=50), nullable=True),
    sa.Column('fecha_produccion', sa.DateTime(), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('cantidad_inicial', sa.Integer(), nullable=False),
    sa.Column('cantidad_disponible', sa.Integer(), nullable=False),
    sa.Column('precio_compra_lote', sa.Float(), nullable=False),
    sa.Column('temperatura_almacenamiento', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id_lote')
    )
    op.create_index(op.f('ix_lote_id_lote'), 'lote', ['id_lote'], unique=False)
    op.create_table('venta',
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('fecha_venta', sa.DateTime(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('descuento', sa.Float(), nullable=True),
    sa.Column('impuestos', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_venta')
    )
    op.create_index(op.f('ix_venta_id_venta'), 'venta', ['id_venta'], unique=False)
    op.create_table('cotizacion',
    sa.Column('id_cotizacion', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('numero_cotizacion', sa.String(length=50), nullable=False),
    sa.Column('fecha_cotizacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('descuento', sa.Float(), nullable=True),
    sa.Column('impuestos', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('id_venta_relacionada', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_venta_relacionada'], ['venta.id_venta'], ),
    sa.PrimaryKeyConstraint('id_cotizacion'),
    sa.UniqueConstraint('numero_cotizacion')
    )
    op.create_index(op.f('ix_cotizacion_estado'), 'cotizacion', ['estado'], unique=False)
    op.create_index(op.f('ix_cotizacion_fecha_cotizacion'), 'cotizacion', ['fecha_cotizacion'], unique=False)
    op.create_index(op.f('ix_cotizacion_id_cotizacion'), 'cotizacion', ['id_cotizacion'], unique=False)
    op.create_table('detalle_venta',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=True),
    sa.Column('id_lote', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id_lote'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['venta.id_venta'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_index(op.f('ix_detalle_venta_id_detalle'), 'detalle_venta', ['id_detalle'], unique=False)
    op.create_table('entrada',
    sa.Column('id_entrada', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_lote', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('fecha_entrada', sa.DateTime(), nullable=False),
    sa.Column('precio_compra_unitario', sa.Float(), nullable=False),
    sa.Column('precio_compra_total', sa.Float(), nullable=False),
    sa.Column('numero_factura_compra', sa.String(length=50), nullable=True),
    sa.Column('proveedor', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id_lote'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_entrada')
    )
    op.create_index(op.f('ix_entrada_id_entrada'), 'entrada', ['id_entrada'], unique=False)
    op.create_table('salida',
    sa.Column('id_salida', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_lote', sa.Integer(), nullable=True),
    sa.Column('tipo_salida', sa.String(length=50), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('fecha_salida', sa.DateTime(), nullable=False),
    sa.Column('motivo', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id_lote'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_salida')
    )
    op.create_index(op.f('ix_salida_id_salida'), 'salida', ['id_salida'], unique=False)
    op.create_table('detalle_cotizacion',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_cotizacion', sa.Integer(), nullable=True),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_cotizacion'], ['cotizacion.id_cotizacion'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_index(op.f('ix_detalle_cotizacion_id_detalle'), 'detalle_cotizacion', ['id_detalle'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalle_cotizacion_id_detalle'), table_name='detalle_cotizacion')
    op.drop_table('detalle_cotizacion')
    op.drop_index(op.f('ix_salida_id_salida'), table_name='salida')
    op.drop_table('salida')
    op.drop_index(op.f('ix_entrada_id_entrada'), table_name='entrada')
    op.drop_table('entrada')
    op.drop_index(op.f('ix_detalle_venta_id_detalle'), table_name='detalle_venta')
    op.drop_table('detalle_venta')
    op.drop_index(op.f('ix_cotizacion_id_cotizacion'), table_name='cotizacion')
    op.drop_index(op.f('ix_cotizacion_fecha_cotizacion'), table_name='cotizacion')
    op.drop_index(op.f('ix_cotizacion_estado'), table_name='cotizacion')
    op.drop_table('cotizacion')
    op.drop_index(op.f('ix_venta_id_venta'), table_name='venta')
    op.drop_table('venta')
    op.drop_index(op.f('ix_lote_id_lote'), table_name='lote')
    op.drop_table('lote')
    op.drop_index(op.f('ix_gasto_id_gasto'), table_name='gasto')
    op.drop_index(op.f('ix_gasto_fecha_gasto'), table_name='gasto')
    op.drop_index(op.f('ix_gasto_categoria'), table_name='gasto')
    op.drop_table('gasto')
    op.drop_index(op.f('ix_alerta_id_alerta'), table_name='alerta')
    op.drop_table('alerta')
    op.drop_index(op.f('ix_usuario_id_usuario'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_producto_nombre_producto'), table_name='producto')
    op.drop_index(op.f('ix_producto_id_producto'), table_name='producto')
    op.drop_index(op.f('ix_producto_estado'), table_name='producto')
    op.drop_table('producto')
    op.drop_index(op.f('ix_seccion_id_seccion'), table_name='seccion')
    op.drop_table('seccion')
    op.drop_index(op.f('ix_rol_id_rol'), table_name='rol')
    op.drop_table('rol')
    op.drop_index(op.f('ix_laboratorio_id_laboratorio'), table_name='laboratorio')
    op.drop_table('laboratorio')
    op.drop_index(op.f('ix_cliente_id_cliente'), table_name='cliente')
    op.drop_table('cliente')
    # ### end Alembic commands ###
